name: demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_database: ^9.0.6
  cached_network_image: ^3.2.0
  cloud_firestore: ^2.2.2
  image_picker: ^0.8.1+2
  flutter_svg: ^1.0.3
  location: ^4.3.0
  geocoding: ^2.0.2
  firebase_storage: ^10.0.7
  alt_sms_autofill: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Akaya
       fonts:
         - asset: fonts/akaya/AkayaTelivigala-Regular.ttf